name: Minimal CI/CD

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Building Docker image..."
          # docker build -t myapp:latest ./app

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Running tests..."
          # python -c "import src.app; print('App imports successfully')"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Deploying to environment..."
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "Deploy to PROD"
            # gcloud run deploy terraform-assessment-prod --image IMAGE
          else
            echo "Deploy to DEV"
            # gcloud run deploy terraform-assessment-dev --image IMAGE

