name: Simple CI/CD

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          gcloud auth activate-service-account --key-file="${{ secrets.GCP_SA_KEY }}"
          gcloud config set project terraform-assess-26565
          gcloud builds submit ./app --tag us-central1-docker.pkg.dev/terraform-assess-26565/terraform-assessment-repo/app:latest
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            gcloud run deploy terraform-assessment-prod \
              --image us-central1-docker.pkg.dev/terraform-assess-26565/terraform-assessment-repo/app:latest \
              --region us-central1 --platform managed --allow-unauthenticated
          else
            gcloud run deploy terraform-assessment-dev \
              --image us-central1-docker.pkg.dev/terraform-assess-26565/terraform-assessment-repo/app:latest \
              --region us-central1 --platform managed --allow-unauthenticated
          fi

